"""Nested waves and sections

Revision ID: c69b08847a80
Revises: 001
Create Date: 2026-06-12 14:45:14.929577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c69b08847a80'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_community_templates_id'), 'community_templates', ['id'], unique=False)
    op.create_index(op.f('ix_community_templates_slug'), 'community_templates', ['slug'], unique=True)
    op.create_table('community_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_community_section_slug')
    )
    op.create_index(op.f('ix_community_sections_community_id'), 'community_sections', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_sections_id'), 'community_sections', ['id'], unique=False)
    op.add_column('communities', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('communities', sa.Column('depth', sa.Integer(), server_default='0', nullable=False))
    op.add_column('communities', sa.Column('path', sa.Text(), server_default='', nullable=False))
    op.add_column('communities', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('communities', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_communities_parent_id'), 'communities', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'communities', 'community_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'communities', 'communities', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_section_id'), 'posts', ['section_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'community_sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_section_id'), table_name='posts')
    op.drop_column('posts', 'section_id')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_constraint(None, 'communities', type_='foreignkey')
    op.drop_index(op.f('ix_communities_parent_id'), table_name='communities')
    op.drop_column('communities', 'is_archived')
    op.drop_column('communities', 'template_id')
    op.drop_column('communities', 'path')
    op.drop_column('communities', 'depth')
    op.drop_column('communities', 'parent_id')
    op.drop_index(op.f('ix_community_sections_id'), table_name='community_sections')
    op.drop_index(op.f('ix_community_sections_community_id'), table_name='community_sections')
    op.drop_table('community_sections')
    op.drop_index(op.f('ix_community_templates_slug'), table_name='community_templates')
    op.drop_index(op.f('ix_community_templates_id'), table_name='community_templates')
    op.drop_table('community_templates')
    # ### end Alembic commands ###
